**1. Import Libraries**

In [43]:
import pandas as pd
import numpy as np

**2. Load Dataset**

In [44]:
df = pd.read_csv('/content/employees.csv')

print("Original Dataset Shape:", df.shape)
df.head()

Original Dataset Shape: (1000, 8)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

**3. Check Data Info**

In [45]:
df.info()

print("\nMissing Values:\n", df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB

Missing Values:
 First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

Duplicate Rows: 0

4. Handle Missing Values

In [46]:
df['Team'].fillna('Unknown', inplace=True)
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)


df['Senior Management'].fillna(False, inplace=True)


df['Salary'].fillna(df['Salary'].median(), inplace=True)
df['Bonus %'].fillna(df['Bonus %'].mean(), inplace=True)

print("Missing values handled.")

Missing values handled.

/tmp/ipykernel_13575/1991836764.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Team'].fillna('Unknown', inplace=True)
/tmp/ipykernel_13575/1991836764.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
/tmp/ipykernel_13575/1991836764.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Senior Management'].fillna(False, inplace=True)
/tmp/ipykernel_13575/1991836764.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Senior Management'].fillna(False, inplace=True)
/tmp/ipykernel_13575/1991836764.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(), inplace=True)
/tmp/ipykernel_13575/1991836764.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Bonus %'].fillna(df['Bonus %'].mean(), inplace=True)

5. Remove Duplicates

In [47]:
before = df.shape[0]

df.drop_duplicates(inplace=True)

after = df.shape[0]

print(f"Removed {before - after} duplicate rows")

Removed 0 duplicate rows

6. Fix Data Formats

In [48]:
df['Start Date'] = pd.to_datetime(df['Start Date'], errors='coerce')


df['First Name'] = df['First Name'].str.strip().str.title()
df['Team'] = df['Team'].str.strip().str.title()
df['Gender'] = df['Gender'].str.capitalize()


df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
df['Bonus %'] = pd.to_numeric(df['Bonus %'], errors='coerce')

print("Data formats corrected.")

Data formats corrected.

In [49]:
print("\nRemaining Missing Values:\n", df.isnull().sum())

print("\nFinal Shape:", df.shape)

Remaining Missing Values:
 First Name           67
Gender                0
Start Date            0
Last Login Time       0
Salary                0
Bonus %               0
Senior Management     0
Team                  0
dtype: int64

Final Shape: (1000, 8)

In [50]:
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,6:53 AM,61933,4.170,True,Unknown
2,Maria,Female,1993-04-23,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,4:47 PM,101004,1.389,True,Client Services

In [51]:
df.tail()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
995,Henry,Female,2014-11-23,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39 PM,96914,1.421,False,Product
998,Larry,Male,2013-04-20,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,6:24 PM,129949,10.169,True,Sales

9. Save Cleaned Dataset

In [52]:
df.to_csv('/content/cleaned_employees.csv', index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.